services:
  unix2tcp:
    build:
      context: .
    command: ["/run/sock/freshrss.sock", "freshrss:80", "mode=660,user=1000,group=1000"]
    volumes:
      - ./sock:/run/sock
    links:
      - freshrss
    depends_on:
      - freshrss

  freshrss:
    image: freshrss/freshrss:latest
    restart: on-failure
    container_name: freshrss_container
    volumes:
      - ./data/freshrss_data:/var/www/FreshRSS/data
      - ./data/freshrss_extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=*/10
      - TZ=Australia/Melbourne
