name: Publish Docker Image

on:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-*'

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      # https://stackoverflow.com/questions/58177786
      - name: Get version
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/yc/unix2tcp:latest
            ghcr.io/yc/unix2tcp:${{ env.GIT_TAG }}
          platforms: linux/amd64,linux/arm64
